### PR TITLE
Add example from https://github.com/coq/coq/issues/16172

### PR DESCRIPTION
**Pull request by JasonGross**
https://github.com/coq/coq/issues/16172#issuecomment-1153276605

h/t @SkySkimmer

### CODE REVIEW

**Comment by SkySkimmer** [comment]
What is h/t?

**Comment by JasonGross** [comment]
> What is h/t?

It stands for "hat tip", and I think the communities I got it from used "h/t X" to mean roughly "thanks to X for finding this / making this / pointing this out / etc"

**Comment by SkySkimmer** [comment]
Please revert, this broke Coq CI

**Comment by JasonGross** [comment]
Link?  What broke on Coq's CI?

I've reverted it, but I'd like to remerge again (#23) once I figure out a way to not break Coq's CI

**Comment by SkySkimmer** [comment]
It times out since the bug is not fixed https://gitlab.com/coq/coq/-/jobs/2633266217

**Comment by JasonGross** [comment]
But the file only takes ~12 seconds to build on my machine.  What's taking time on Coq CI?

**Pull request merged**
